# Generated by Django 5.0.6 on 2024-07-05 11:59

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='MeinModell',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titel', models.CharField(max_length=200)),
                ('inhalt', models.TextField()),
                ('erstellt_am', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
